\input texinfo

@ifnottex
@paragraphindent 0
@end ifnottex
@titlepage
@title Руководство по использованию
@end titlepage

@node Top
@top Это руководство по использованию и сборке калькулятора.
Калькулятор поддерживает вычисления из полученной строки. Подстановку значения для переменной X или постройка графика по полученной формуле.

	Установка программы:

Чтобы собрать приложение и отправить его на рабочий стол: make install

Для очистки всех файлов, созданных в ходе компиляции: make clean

Для архивации файлов, нужных для сборки проекта: make dist

Для удаления с рабочего стола папки с приложением: make uninstall

Для запуска тестов: make test

Для запуска проверки покрытия кода тестам: "make" or "make gcov_report"

Для проверки на стиль: make check


	Калькулятор:

Для того, чтобы пользоваться калькулятором вы должны ввести в поле ввода выражение при помощи клавиш в приложении и нажать на кнопку "=", после чего в него вернется значение, подсчитанное калькулятором.

Если в выражении была найдена какая-либо ошибка, вернется значение NAN.

Если в выражении будет найден x, то откроется новое окно, где вам будет дан выбор: Подставить какое-то конкретное значение x или построить график.

При нажатии на кнопку "Построить график" появится новое окно, где вы можете подобрать нужные вам области определения для X и Y, ограниченные значениями -1000000 и 1000000. Для построения графика нужно еще раз нажать на кнопку "Построить график"

@bye
