\input texinfo

@ifnottex
@paragraphindent 0
@end ifnottex

@node Top
@top 3DViewer.


@top    Установка и запуск

Для установки программы введите команду: make install в папке src.

Исполняемый фаил помещается в папку src под именем 3DViewer

Почистить наделанное можно командой: make clean

Так же можно сделать архив дистрибутива: make dist

Чтобы удалить make uninstall



@top   Простейший 3DВьювер 

Для начала работы необходимо загрузить модель, при помощи кнопки открыть файл. Наш вьевер

работает с файлами типа OBJ.

Для поворота модели необходимо задать угол в поле над кнопками поворота.

Для смещения модели по осям необходимо задать велечину смещения в поле ввода мнжду кнопками.

Для отрисовки точек поставить чек в поле DOTs.

В остальных полях можно выбрать цвет и тип линий и вершин.

Спасибо за внимание!

@bye

